<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="nosotros.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>Ubicaciones en Mapa</title>
    <?php include 'template\cabecera.php'; ?>
</head>

<body>
    <div class="titulo"  id ="ubicacion">Nuestras Tiendas</div>
    <div class="ubicacion" >
        <div class="location-card">
            <div class="location-header-custom">AREQUIPA. SACHACA</div>
            <div class="location-body-custom">
                <div class="location-map-custom">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15958.012477431872!2d-77.07367672741332!3d-12.130803621246364!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x910b9c603c8a88e9%3A0x285f4df3d49d9789!2sVilla%20El%20Triunfo%2C%20Per%C3%BA!5e0!3m2!1sen!2spe!4v1649063483994!5m2!1sen!2spe" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
                <div class="location-info-custom">
                    <div class="location-icon-custom"></div>
                    <div class="location-address-custom">VILLA EL TRIUNFO ZN.B.Mz.f Lt.1</div>
                </div>
                <div class="location-info-custom">
                    <div class="location-icon-custom"></div>
                    <div class="location-phone-custom">945809532</div>
                </div>
            </div>
        </div>
        <div class="location-card">
            <div class="location-header-custom">AREQUIPA CERRO COLORADO</div>
            <div class="location-body-custom">
                <div class="location-map-custom">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d119942.35803977926!2d-71.56709846770397!3d-16.3833486708868!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x910b9ca7bf13971d%3A0x7a2bbf7f7d1ffeba!2sCerro%20Colorado%2C%20Arequipa!5e0!3m2!1sen!2spe!4v1649056491872!5m2!1sen!2spe" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
                <div class="location-info-custom">
                    <div class="location-icon-custom"></div>
                    <div class="location-address-custom">asc.via las flores zn.1 Mz.k Lt.2 Av.54</div>
                </div>
                <div class="location-info-custom">
                    <div class="location-icon-custom"></div>
                    <div class="location-phone-custom">941965090</div>
                </div>
            </div>
        </div>
    </div>
    <HR>
    </HR>
    <div class="INFOCOBRE" style="text-align: center;" id="INFORMACION">
        <h1>INFORMACION <span class="highlight">COBRE</span> INOX</h1>
    </div>


    <div class="contANGE my-5" >
        <div class="row">
            <div class="col-lg-6">

                <h2 class="cobre-title">Cobre Inox</h2>
                <p class="text-muted">Termas solares de cobre inoxidable. Somos líderes en la fabricación y distribución de sistemas de termas solares de alta calidad, diseñados para proporcionar agua caliente de manera eficiente y sostenible. Nuestros productos están elaborados con los mejores materiales y tecnologías disponibles en el mercado, garantizando un rendimiento excepcional y durabilidad a largo plazo.</p>

                <h4>Detalles</h4>

                <ul class="cobre-lista list-unstyled">

                    <li>Termas solares 100% acero inoxidable</li>
                    <li>Agua caliente 24h</li>
                    <li>Para el hogar, hotelería</li>
                    <li>Garantía 5 años</li>
                    <li>Instalación profesional incluida</li>
                    <li>Resistente a la corrosión y la oxidación</li>
                    <li>Ahorro energético</li>
                    <li>Materiales de alta calidad</li>
                </ul>


            </div>

            <div class="col-lg-6">
                <h2 class="tecnico-title">Técnico en Cobre Inox</h2>
                <p class="text-muted">Soldador en Sachaca, Arequipa, Perú. Estudió operaciones en Instituto Tecnológico Privado Flavisur. Estudió en Independencia Americana. Vive en Sachaca, Arequipa, Perú. Experiencia en la industria del cobre inoxidable: 10 años. Certificaciones en soldadura de alta precisión. Conocimiento avanzado en tecnologías de energía solar. Comprometido con la excelencia y la satisfacción del cliente.</p>
                <img src="Nueva carpeta\img\Diseño sin título (1) (1).png" alt="Imagen de ejemplo" class="img-fluid">
            </div>

        </div>
        <div class="row mt-4">
            <div class="col-md-12 text-center">
                <h2 class="mb-4">Fotos</h2>
                <div class="d-flex justify-content-center">
                    <img src="Nueva carpeta\img\223947434_1474595796206495_8632820481406800420_n (1).jpg" alt="Imagen 1" class="img-fluid mx-2">
                    <img src="Nueva carpeta\img\223947434_1474595796206495_8632820481406800420_n (1).jpg" alt="Imagen 2" class="img-fluid mx-2">
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-12">
                <h2>Testimonios</h2>
                <div class="testimonios">
                    <blockquote class="blockquote text-center">
                        <p class="mb-0">"El servicio proporcionado por el técnico en cobre inoxidable fue excepcional. ¡Altamente recomendado!"</p>
                        <footer class="blockquote-footer">- Cliente satisfecho</footer>
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-12">
                <h2>Contacto</h2>
                <p>¡Contáctanos hoy para obtener más información o para programar una consulta gratuita!</p>
                <p>Teléfono: +51 945809532</p>
                <p>Correo electrónico: info@cobreinox.com</p>
                <p>Dirección: [VILLA EL TRIUNFO ZN.B.Mz.f Lt.1]</p>
                <p>Horario de atención: Lunes a Viernes, 9:00 AM - 5:00 PM</p>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row mt-4">
            <div class="col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Eficiencia Energética</h5>
                        <p class="card-text">Nuestras termas solares están diseñadas para aprovechar al máximo la energía del sol y convertirla en agua caliente para su uso en el hogar, la hotelería y otras aplicaciones comerciales. Con nuestros sistemas, puedes disfrutar de agua caliente las 24 horas del día, de manera sostenible y económica.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Calidad Superior</h5>
                        <p class="card-text">Utilizamos cobre inoxidable de alta calidad en la fabricación de nuestros productos, lo que garantiza resistencia a la corrosión y la oxidación, así como una vida útil prolongada. Nuestras termas solares están construidas para soportar las condiciones más exigentes y proporcionar un rendimiento confiable a lo largo del tiempo.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Instalación Profesional</h5>
                        <p class="card-text">Ofrecemos servicios de instalación profesional incluidos en la compra de nuestros sistemas de termas solares. Nuestro equipo de técnicos expertos se encargará de instalar tu sistema de manera rápida y eficiente, asegurando un funcionamiento óptimo desde el primer día.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Garantía de 5 Años</h5>
                        <p class="card-text">Respaldamos la calidad y fiabilidad de nuestros productos con una garantía de 5 años. Esto te brinda tranquilidad y confianza en tu inversión, sabiendo que estamos comprometidos a ofrecer productos de la más alta calidad y satisfacción al cliente.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
<?php include 'template\footer.PHP'; ?>

</html>