<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tanques y Tecnologías Solares</title>
    <link rel="stylesheet" href="terma.css">
    <?php include 'template\cabecera.php'; ?>

</head>

<body>
    <div class="infotermas">
        <div class="infottermas2">
            <h1 class="TILTLE">Tipos de Tanques y Tecnologías Solares</h1>
            <p>En Termas Solares, ofrecemos una variedad de tanques y tecnologías solares diseñadas para proporcionar eficiencia y durabilidad en la captura y almacenamiento de energía solar. Nuestros productos están construidos con los más altos estándares de calidad y están diseñados para adaptarse a las necesidades específicas de cada cliente. Ofrecemos tanques de diferentes tamaños y capacidades, así como tecnologías solares avanzadas que garantizan un rendimiento óptimo y una larga vida útil. ¡Confíe en Termas Solares para obtener la mejor solución en energía solar!</p>
        </div>


        <div class="tanques-conta" id="tanques">
    <h2>Tanques</h2>
    <div class="tanques-section">
        <div class="card">
            <img src="Nueva carpeta\img 2\img.webp" alt="Acero Inoxidable">
            <div class="card-body">
                <h3>Acero inoxidable</h3>
                <p>Tanques fabricados con acero inoxidable de alta calidad, ideales para resistir la corrosión y garantizar una larga vida útil.</p>
            </div>
        </div>
        <div class="card">
            <img src="Nueva carpeta\img 2\mg2.jpg" alt="Acero Lacado">
            <div class="card-body">
                <h3>Acero lacado</h3>
                <p>Tanques recubiertos con una capa de pintura especial que proporciona protección contra la corrosión y los elementos externos, asegurando una excelente durabilidad.</p>
            </div>
        </div>
    </div>
</div>
<HR></HR>

<div class="solar-panels-contex" id="paneles-solares">
    <h1>Paneles Solares</h1>
    <div class="panel-grid">
        <div class="solar-panel">
            <img src="Nueva carpeta\img 2\panel.jpg" alt="Panel con Rejilla de Tubos de Cobre Rígido">
            <h2>Rejilla de Tubos de Cobre Rígido</h2>
            <p>Los paneles solares con rejilla de tubos de cobre rígido son una opción eficiente para la captura de energía solar. La disposición de los tubos de cobre garantiza una mayor superficie de captación, lo que resulta en una mayor eficiencia energética.</p>
        </div>
        <div class="solar-panel">
            <img src="Nueva carpeta\img 2\66217bb1e010fa000d431fd2.jpg" alt="Panel con Tubos al Vacío">
            <h2>Tubos al Vacío</h2>
            <p>Los paneles solares con tubos al vacío son ideales para maximizar la captura de energía solar incluso en condiciones de baja radiación. Estos tubos están diseñados para mantener el vacío en su interior, lo que minimiza la pérdida de calor y asegura un rendimiento óptimo.</p>
        </div>
        <div class="solar-panel">
            <img src="Nueva carpeta\img 2\Diseño sin título (5).png" alt="Modelo Omega Plus">
            <h2>Modelo Omega Plus</h2>
            <p>El modelo Omega Plus es una opción avanzada en paneles solares. Con características innovadoras y un diseño robusto, este modelo garantiza un alto rendimiento y una larga vida útil. Es una excelente elección para aquellos que buscan una solución duradera y eficiente en energía solar.</p>
        </div>
    </div>
</div>
<HR></HR>
<div class="SOLDADURAS" id="soldaduras">
    <h1 class="main-title">TECNOLOGÍA EN SOLDADURAS</h1>

    <div class="section">
        <div class="content">
            <h2 class="sub-title">Soldadura TIG: Calidad y Limpieza Excepcionales</h2>
            <p class="text">Descubre cómo la soldadura TIG proporciona una de las soldaduras más limpias y de alta calidad disponibles en el mercado. Con esta técnica, eliminamos por completo la posibilidad de inclusiones en el metal depositado, garantizando una calidad excepcional y una durabilidad incomparable. En Termas Solares Arequipa, nos enorgullecemos de ofrecer soldaduras TIG que superan las expectativas de nuestros clientes en términos de calidad y durabilidad.</p>
        </div>
        <div class="image-container">
            <figure>
                <img src="Nueva carpeta\img 2\soldarura.jpg" alt="Soldadura TIG">
                <figcaption>Soldadura TIG</figcaption>
            </figure>
        </div>
    </div>

    <div class="section">
        <div class="content">
            <h2 class="sub-title">Soldadura Autógena: Excelencia en la Unión de Tubos de Cobre</h2>
            <p class="text">Descubre los beneficios de la soldadura autógena, una técnica que aplicamos en todos nuestros trabajos de unión de tubos de cobre y mantenimiento. Con la llama de acetileno y oxígeno, podemos ajustar perfectamente las características de la soldadura y el punto de fusión, garantizando una unión sólida y duradera. En Termas Solares Arequipa, nuestra soldadura autógena es sinónimo de alta calidad y excelencia en la producción.</p>
        </div>
        <div class="image-container">
            <figure>
                <img src="Nueva carpeta\img 2\autogena.jpg" alt="Soldadura Autógena">
                <figcaption>Soldadura Autógena</figcaption>
            </figure>
        </div>
    </div>

    <div class="section">
        <div class="content">
            <h2 class="sub-title">Soldadura MIG-MAG: Eficiencia y Productividad en la Soldadura</h2>
            <p class="text">Explora los beneficios de la soldadura MIG-MAG, el método más utilizado en Europa occidental, Estados Unidos y Japón debido a su elevada productividad y facilidad de automatización. En Termas Solares Arequipa, empleamos esta técnica para garantizar soldaduras limpias y de alta calidad, cumpliendo con todas las medidas de protección para el medio ambiente. Confía en nosotros para obtener resultados eficientes y sostenibles en tus proyectos de soldadura.</p>
        </div>
        <div class="image-container">
            <figure>
                <img src="Nueva carpeta\img 2\curso-soldadura-mig-mag.jpg" alt="Soldadura MIG-MAG">
                <figcaption>Soldadura MIG-MAG</figcaption>
            </figure>
        </div>
    </div>
</div>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>
<?php include 'template\footer.PHP'; ?>

</html>