<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tienda en línea</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" href="template\cabecera.css">
</head>



<body>
<footer class="mi-footer">
    <div class="mi-container">
      <div class="mi-footer-content">
        <div class="mi-footer-section">
          <h3>Contactos</h3>
          <ul>
            <li>950770631</li>
            <li>945809532</li>
            <li>941965090</li>
          </ul>
        </div>
        <div class="mi-footer-section">
          <h3>Tecnología</h3>
          <ul>
            <li>Soldadura TIG</li>
            <li>Soldadura Autógena</li>
            <li>Soldadura MIG MAG</li>
            <li>Opción 4</li>
          </ul>
        </div>
        <div class="mi-footer-section">
          <h3>Beneficios</h3>
          <ul>
            <li>Somos Fabricantes</li>
            <li>Agua Caliente 24h</li>
            <li>Ahorre Dinero</li>
            <li>Energía Natural</li>
          </ul>
        </div>
        <div class="mi-footer-section">
          <h3>Síguenos</h3>
          <div class="mi-social-icons">
            <a href="https://www.facebook.com/alfredo.chani" target="_blank"><i class="fab fa-facebook"></i></a>
            <a href="https://www.instagram.com/tusitio" target="_blank"><i class="fab fa-instagram"></i></a>
            <a href="mailto:info@tusitio.com"><i class="fas fa-envelope"></i></a>
            <a href="https://www.youtube.com/@termassolarcobreinox960" target="_blank"><i class="fab fa-youtube"></i></a>
          </div>
        </div>
      </div>
    </div>

    <div class="mi-contact-info">
            <img src="Nueva carpeta\img\Captura (1) (1).png" alt="Imagen de título">
            <BR></BR>
            <p>Estamos aquí para responder a todas sus preguntas y ayudarle a dar el paso hacia un sistema de calefacción de agua más eficiente y amigable con el medio ambiente en todos los departamentos y provincias de Arequipa. ¡Póngase en contacto con nosotros hoy mismo para programar una visita gratuita a su hogar y obtener su presupuesto personalizado! Termas Solar Cobre Inox está listo para servirle en toda Arequipa.</p>
          </div>
        
  </footer>



</body>